### ISSUE TITLE
Create a Toast component

### ISSUE THREAD

**Issue by iguit0** [ufv-crp/web-music#44]
> Notistack is a Snackbar library which makes it extremely easy to display notifications on your web apps. It is highly customizable and enables you to stack snackbars/toasts on top of one another.

### Reference :mag_right: 

- [API](https://iamhosseindhv.com/notistack/api)
- [Examples](https://iamhosseindhv.com/notistack/demos)

**Comment by ghost** [comment]
It's not necessary anymore because the package [Noti Stack](https://github.com/iamhosseindhv/notistack) give us all kinds of toasts done
